name: SignStatus
main: xpyctum\SignStatus\SignStatus
version: 3.0.3
api: 3.0.0
author: "xpyctum"
description: "A plugin for displaying the server's current stats in-game"
load: POSTWORLD
permissions:
 signstatus:
  default: op
  description: "Allows players to create and destroy status signs"
  children:
   signstatus.break:
    default: op
    description: "Allows players to destroy status signs"
   signstatus.create:
    default: op
    description: "Allows players to create status signs"